#!/usr/bin/env python3
# Copyright (c) 2026 Boopie contributors
# SPDX-License-Identifier: Apache-2.0

"""Builds the pinyin input's dictionary: every syllable, and the characters
it spells, most used first.

  pip install pypinyin
  pip download --no-deps --no-binary :all: jieba && tar xzf jieba-*.tar.gz
  python3 tools/boopie/gen_pinyin.py --jieba jieba-0.42.1/jieba/dict.txt

writes esp32/components/boopie/ime/boopie_pinyin_dict.c. Characters are the
GB2312 hanzi Boopie's UI font draws; how much each is used comes from
jieba's word frequencies (each word's count to each of its characters), and
readings from pypinyin (both MIT). Syllables are listed most used first, so
the input offers the likelier spelling of a key sequence first; ü is v.
A polyphone's main reading counts in full, its others at a hundredth, so
它 doesn't come up early for yi.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

from pypinyin import Style, pinyin

ROOT = Path(__file__).resolve().parents[2]
GLYPHS = ROOT / "esp32" / "components" / "boopie" / "font" / "boopie_ui_metrics_data.c"
OUT = ROOT / "esp32" / "components" / "boopie" / "ime" / "boopie_pinyin_dict.c"
PER_SYLLABLE = 80   # candidates kept for a syllable: past these nobody pages


def font_chars() -> set[int]:
    text = GLYPHS.read_text()
    table = text[text.index("boopie_ui_cps[]"):]
    table = table[:table.index("};")]
    return {int(h, 16) for h in re.findall(r"0x([0-9a-f]{4,5})", table)}


def gb2312_hanzi() -> list[str]:
    out = []
    for b1 in range(0xB0, 0xF8):
        for b2 in range(0xA1, 0xFF):
            try:
                out.append(bytes([b1, b2]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--jieba", type=Path, required=True, help="jieba's dict.txt")
    args = ap.parse_args()

    freq: dict[str, int] = defaultdict(int)
    for line in args.jieba.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1].isdigit():
            for ch in parts[0]:
                freq[ch] += int(parts[1])

    drawn = font_chars()
    syllables: dict[str, list[tuple[int, str]]] = defaultdict(list)
    for ch in gb2312_hanzi():
        if ord(ch) not in drawn or not freq.get(ch):
            continue
        main_reading = pinyin(ch, style=Style.NORMAL)[0][0]
        for reading in sorted(set(pinyin(ch, style=Style.NORMAL, heteronym=True)[0])):
            # Rare readings of a polyphone go to the back of their syllable.
            weight = freq[ch] if reading == main_reading else max(1, freq[ch] // 100)
            reading = reading.replace("ü", "v")
            if re.fullmatch(r"[a-z]+", reading):
                syllables[reading].append((weight, ch))

    rows = []
    for py, chars in syllables.items():
        chars.sort(key=lambda fc: (-fc[0], fc[1]))
        rows.append((sum(f for f, _ in chars), py, "".join(c for _, c in chars[:PER_SYLLABLE])))
    rows.sort(key=lambda r: (-r[0], r[1]))

    lines = [
        "/*",
        " * Copyright (c) 2026 Boopie contributors",
        " * SPDX-License-Identifier: Apache-2.0",
        " *",
        " * Generated by tools/boopie/gen_pinyin.py: don't edit. Readings from pypinyin",
        " * and frequencies from jieba's dictionary (both MIT).",
        " */",
        "",
        '#include "boopie_pinyin.h"',
        "",
        "/* Most used syllable first; each with its characters, most used first. */",
        "const boopie_pinyin_entry_t BOOPIE_PINYIN_DICT[] = {",
    ]
    for _, py, chars in rows:
        lines.append(f'    {{ "{py}", "{chars}" }},')
    lines += ["};", "", "const int BOOPIE_PINYIN_COUNT = (int)(sizeof(BOOPIE_PINYIN_DICT) / sizeof(BOOPIE_PINYIN_DICT[0]));", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    n = sum(len(c) for _, _, c in rows)
    print(f"{len(rows)} syllables, {n} characters ({len(set(''.join(c for _, _, c in rows)))} distinct) -> {OUT}")


if __name__ == "__main__":
    main()
