#!/usr/bin/env python3
# Copyright (c) 2026 Boopie contributors
# SPDX-License-Identifier: Apache-2.0
"""Times the song's lyrics a character at a time for the karaoke: the words
faster-whisper heard (asr.json: segments with word timestamps), corrected to
the lyrics as written, into web/lyrics.js.

  python3 tools/boopie/promo/lyrics.py --asr work/song/asr.json --out tools/boopie/promo/web/lyrics.js
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

# The lyrics as sung, one entry per heard segment; "|" breaks it into the lines
# shown. A token is a Chinese character or a run of Latin letters.
LINES = [
    "Hi～ 布比布比|布比布比",
    "Hi～",
    "Hi～ 布比",
    "圆圆的小屏幕|亮起粉色的心",
    "早安对我眨眨眼|天气它都记得清",
    "扫一扫就上线|Wi-Fi 蓝牙都连通",
    "走到天涯海角|网络也畅通无阻",
    "轻轻叫一声 Muse|它就懂你",
    "远方的电脑|也替你搞定",
    "布比布比布比|你的 AI 小伙伴",
    "会听会说会撒娇|陪我每一天",
    "一句话|它就去做|works with Muse",
    "小小的它|装着大大的宇宙",
    "换上新皮肤|四十多种都好看",
    "戳一戳 歪一歪|小游戏 玩不完",
    "布比布比布比|带我去它的小世界",
    "种花钓鱼去冒险|下雨就回家",
    "节日挂满小彩灯|一年四季都不一样",
    "布比布比|一直在你身旁",
    "布比布比|你的 AI 小伙伴",
    "布比布比布比布比布比|布比布比布比布比布比",
]
TOKEN = re.compile(r"[A-Za-z][A-Za-z\-]*～?|[^\sA-Za-z|～。，,.!！?？]")


def heard(segment) -> list[tuple[float, float]]:
    """A (start, end) per token heard: a word of several characters split evenly."""
    out = []
    for s, e, w in segment["words"]:
        toks = TOKEN.findall(w.strip())
        toks = toks or [w]
        for i in range(len(toks)):
            out.append((s + (e - s) * i / len(toks), s + (e - s) * (i + 1) / len(toks)))
    return out


def main() -> None:
    a = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    a.add_argument("--asr", type=Path, required=True)
    a.add_argument("--out", type=Path, required=True)
    args = a.parse_args()
    segs = json.loads(args.asr.read_text())
    assert len(segs) == len(LINES), (len(segs), len(LINES))
    shown = []
    for seg, text in zip(segs, LINES):
        times = heard(seg)
        parts = text.split("|")
        toks = [[t for t in TOKEN.findall(p)] for p in parts]
        flat = [t for p in toks for t in p]
        n, m = len(flat), len(times)
        # map token i of the lyric onto the heard ones, in proportion
        starts = [times[min(m - 1, int(i * m / n))][0] for i in range(n)]
        # spread out tokens heard at the same moment, and keep time running forward
        end = seg["end"]
        i = 0
        while i < n:
            j = i
            while j + 1 < n and starts[j + 1] <= starts[i] + 0.02:
                j += 1
            nxt = starts[j + 1] if j + 1 < n else end
            for k in range(i, j + 1):
                starts[k] = starts[i] + (nxt - starts[i]) * (k - i) / (j - i + 1)
            i = j + 1
        k = 0
        for p in toks:
            line = []
            for t in p:
                line.append([t, round(starts[k], 3)])
                k += 1
            shown.append({"t0": line[0][1], "t1": round(starts[k] if k < n else end, 3), "chars": line})
        if n != m:
            print(f"note: {text!r}: {n} tokens to {m} heard")
    # a line stays up until the next one starts (at most 1.2 s after its last character)
    for i, l in enumerate(shown):
        last = l["chars"][-1][1]
        nxt = shown[i + 1]["t0"] if i + 1 < len(shown) else last + 1.5
        l["t1"] = round(min(nxt, max(l["t1"], last + 0.4) + 1.2), 3)
    args.out.write_text("// Generated by lyrics.py: the song's lines, each character with when it's sung.\n"
                        f"const LYRICS = {json.dumps(shown, ensure_ascii=False)};\n")
    print(len(shown), "lines")


if __name__ == "__main__":
    main()
