#!/usr/bin/env python3
# Copyright (c) 2026 Boopie contributors
# SPDX-License-Identifier: Apache-2.0
"""What the video dances to, from the song's stems: the drums' kicks and snares
(the drum stem, by band), and the lead vocal's loudness 30 times a second (for
the mascots singing along), into web/beats.js.

  python3 tools/boopie/promo/stems.py --drums drums.mp3 --vocals vocals.mp3 --out tools/boopie/promo/web/beats.js
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import librosa
import numpy as np


def hits(y, sr, lo, hi, gap):
    """Hits in a band: its onsets, the stronger 60 %, at least `gap` seconds apart."""
    s = np.abs(librosa.stft(y, n_fft=1024, hop_length=256))
    f = librosa.fft_frequencies(sr=sr, n_fft=1024)
    band = librosa.amplitude_to_db(s[(f >= lo) & (f < hi)].mean(0) + 1e-6)
    flux = np.maximum(0, np.diff(band, prepend=band[0]))
    on = librosa.onset.onset_detect(onset_envelope=flux, sr=sr, hop_length=256, delta=0.12, wait=6)
    strength = flux[on]
    keep = strength >= np.percentile(strength, 40)
    out = []
    for t in librosa.frames_to_time(on[keep], sr=sr, hop_length=256):
        if not out or t - out[-1] >= gap:
            out.append(round(float(t), 3))
    return out


def main() -> None:
    a = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    a.add_argument("--drums", type=Path, required=True)
    a.add_argument("--vocals", type=Path, required=True)
    a.add_argument("--out", type=Path, required=True)
    args = a.parse_args()
    y, sr = librosa.load(args.drums, sr=22050, mono=True)
    kicks = hits(y, sr, 30, 150, 0.4)
    snares = hits(y, sr, 1500, 6000, 0.4)
    v, vsr = librosa.load(args.vocals, sr=22050, mono=True)
    rms = librosa.feature.rms(y=v, frame_length=1470, hop_length=735)[0]   # 30 a second
    vox = np.clip(rms / np.percentile(rms[rms > 0.01], 95), 0, 1)
    args.out.write_text("// Generated by stems.py: drum hits (s) and the lead vocal's level, 30 a second.\n"
                        f"const KICKS = {json.dumps(kicks)};\nconst SNARES = {json.dumps(snares)};\n"
                        f"const VOX = {json.dumps([round(float(x), 2) for x in vox])};\n")
    print(len(kicks), "kicks", len(snares), "snares", len(vox), "vocal frames")


if __name__ == "__main__":
    main()
