/*
 * Copyright (c) 2026 Boopie contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by tools/boopie/world_art.py: do not edit.
 */

#pragma once

#include <stdint.h>

/* A picture: indexes into boopie_art_palette (0: see-through), row by row;
 * (ax, ay) where it stands, from its top left. */
typedef struct {
    uint16_t w, h;
    int16_t ax, ay;
    const uint8_t *px;
} boopie_art_t;

typedef enum {
    BOOPIE_ART_BG_DOWN,
    BOOPIE_ART_BG_DOWN_FANCY,
    BOOPIE_ART_BG_UP,
    BOOPIE_ART_BG_UP_STARS,
    BOOPIE_ART_TV_OLD,
    BOOPIE_ART_TV_FLAT,
    BOOPIE_ART_BOOKSHELF,
    BOOPIE_ART_RADIO,
    BOOPIE_ART_STAIRS_UP,
    BOOPIE_ART_STAIRS_DOWN,
    BOOPIE_ART_TABLE,
    BOOPIE_ART_PLANT,
    BOOPIE_ART_PLANT_BIG,
    BOOPIE_ART_BOWL_FULL,
    BOOPIE_ART_BOWL_EMPTY,
    BOOPIE_ART_BED,
    BOOPIE_ART_BED_BIG,
    BOOPIE_ART_WARDROBE,
    BOOPIE_ART_MIRROR,
    BOOPIE_ART_DESK,
    BOOPIE_ART_PICTURE,
    BOOPIE_ART_POSTER,
    BOOPIE_ART_SOFA,
    BOOPIE_ART_LAMP,
    BOOPIE_ART_AQUARIUM,
    BOOPIE_ART_TROPHY,
    BOOPIE_ART_STAR_LAMP,
    BOOPIE_ART_BEANBAG,
    BOOPIE_ART_TELESCOPE,
    BOOPIE_ART_WINDOW_DAY,
    BOOPIE_ART_WINDOW_NIGHT,
    BOOPIE_ART_DOOR_OUT,
    BOOPIE_ART_RUG_SMALL,
    BOOPIE_ART_RUG_BIG,
    BOOPIE_ART_RUG_ROUND,
    BOOPIE_ART_HINT_ZZZ,
    BOOPIE_ART_HINT_SHIRT,
    BOOPIE_ART_HINT_GAME,
    BOOPIE_ART_HINT_PEN,
    BOOPIE_ART_HINT_NOTE,
    BOOPIE_ART_HINT_BOOK,
    BOOPIE_ART_HINT_FOOD,
    BOOPIE_ART_HINT_UP,
    BOOPIE_ART_HINT_DOWN,
    BOOPIE_ART_HINT_DOOR,
    BOOPIE_ART_HINT_INFO,
    BOOPIE_ART_HINT_BANG,
    BOOPIE_ART_COUNT,
} boopie_art_id_t;

#define BOOPIE_ART_COLOURS 173
extern const uint32_t boopie_art_palette[BOOPIE_ART_COLOURS];   /* 0xRRGGBB */
extern const boopie_art_t boopie_art[BOOPIE_ART_COUNT];

